services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pfc-app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: pfc-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
